name: my_first_riverpod
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.0
  dots_indicator: ^3.0.0
  flash: ^3.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.4.10
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.0.0
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.10
  image_picker: ^1.0.7
  json_annotation: ^4.8.1
  numberpicker: ^2.1.2
  path: null
  path_provider: any
  sembast: ^3.6.0
  table_calendar: ^3.1.0
  uuid: ^4.3.3
  go_router: ^13.2.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  rxdart: ^0.27.7

dev_dependencies:
  auto_route: ^7.8.4
  very_good_analysis: ^5.1.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/boop.mp3
    - assets/dingdingding.mp3
    - assets/pip.mp3
    - assets/endbeep.mp3
    - images/
    - assets/fonts/
    - assets/icons/
    - assets/icons/sidebar/
    - assets/icons/factoring/
    - assets/icons/ap_ar/
    - assets/icons/cash_flow/
    - assets/icons/status_icons/
    - assets/icons/arrows/
  fonts:
    - family: Exo2-Bold
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
    - family: Exo2-Italic
      fonts:
        - asset: assets/fonts/Exo2-Italic.ttf
    - family: Exo2-Regular
      fonts:
        - asset: assets/fonts/Exo2-Regular.ttf
    - family: Exo2-SemiBold
      fonts:
        - asset: assets/fonts/Exo2-SemiBold.ttf
