name: my_first_riverpod
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-226.0.dev <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.1
  flutter_riverpod: ^1.0.1
  hooks_riverpod: ^1.0.2
  json_annotation: ^4.4.0
  numberpicker: ^2.1.1
  path: ^1.8.1
  path_provider: ^2.0.8
  sembast: ^3.1.1+1
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
